apiVersion: apps/v1
kind: Deployment
metadata:
  name: fds-main
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fds-main
  template:
    metadata:
      labels:
        app: fds-main
    spec:
      containers:
        - name: fds-main
          image: ghcr.io/chandrasekhar818/fds-main:f84a88a2a223b0cdc358ae48b45dff3fae26e90d
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
      imagePullSecrets:
        - name: ghcr-secret
